global:
  smtp_smarthost: "smtp.gmail.com:587"
  smtp_from: "olobatoluwah@gmail.com"
  smtp_auth_username: "olobatoluwah@gmail.com"
  smtp_auth_password: "sk6qbBCeo!FGRjoP"
  smtp_require_tls: true

route:
  group_by: ["alertname"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: "email_alert"

receivers:
  - name: "email_alert"
    email_configs:
      - to: "olobatoluwah@gmail.com"
        send_resolved: true